/outside_robots/robot_news_station_giskard:
  ros__parameters:
    robot_name: "Giskard"

/outside_robots/robot_news_station_bb8:
  ros__parameters:
    robot_name: "BB8"

/outside_robots/robot_news_station_daneel:
  ros__parameters:
    robot_name: "Daneel"

/inside_robots/robot_news_station_jander:
  ros__parameters:
    robot_name: "Jander"

/inside_robots/robot_news_station_c3p0:
  ros__parameters:
    robot_name: "C3P0"
